project:
  type: website
  output-dir: docs

website:
  title: "ds2025s"
  navbar:
    left:
      - href: project1.ipynb
        text: Project1
      - href: project2.ipynb
        text: Project2
      - href: report.ipynb
        text: Report

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



